pesan_motivasi = [
        "Jangan malas! Ingat tujuanmu! 💪",
        "Setiap detik adalah peluang untuk sukses 🔥",
        "Kamu yang sekarang adalah CEO masa depan 😎",
        "Kesuksesan dimulai dari langkah kecil hari ini 🌟",
        "Jangan menyerah, mimpi besar butuh usaha besar! 🚀",
        "Kegagalan adalah guru terbaik untuk sukses berikutnya 📚",
        "Kamu lebih kuat dari yang kamu pikirkan 💪",
        "Hari ini adalah kesempatan baru untuk menjadi lebih baik 🌈",
        "Percayalah pada dirimu sendiri, kamu bisa melakukannya! ✨",
        "Setiap usaha yang kamu lakukan akan membuahkan hasil 🌱",
        "Kesuksesan adalah hasil dari kerja keras dan ketekunan 💼",
        "Jangan takut gagal, karena kegagalan adalah bagian dari perjalanan sukses 🌟",
        "Setiap hari adalah kesempatan baru untuk menjadi lebih baik 🌞",
        "Kamu adalah arsitek dari masa depanmu sendiri 🏗️",
        "Jangan biarkan rasa takut menghentikan langkahmu 🚶‍♂️",
        "Mimpi besar membutuhkan usaha besar, jangan menyerah! 💪",
        "Kamu lebih dekat dengan kesuksesan daripada yang kamu pikirkan 🌈",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Jangan pernah berhenti belajar, karena hidup adalah proses belajar 📚",
        "Kamu adalah pahlawan dalam cerita hidupmu sendiri 🦸‍♂️",
        "Jangan biarkan kegagalan mendefinisikanmu, bangkitlah! 🔥",
        "Setiap usaha yang kamu lakukan adalah investasi untuk masa depanmu 💰",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah inspirasi bagi orang lain, teruslah bersinar ✨",
        "Setiap hari adalah kesempatan untuk memulai lagi 🌅",
        "Jangan biarkan keraguan menghentikanmu, kamu bisa melakukannya! 💪",
        "Kesuksesan dimulai dari keberanian untuk bermimpi besar 🌟",
        "Kamu lebih kuat dari rintangan yang kamu hadapi 💪",
        "Jangan pernah meremehkan kekuatan dari usaha kecil yang konsisten 🛠️",
        "Kamu adalah penulis dari cerita hidupmu sendiri 📖",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya kekuatan untuk mengubah dunia di sekitarmu 🌍",
        "Jangan takut untuk bermimpi besar, karena mimpi adalah awal dari segalanya 🌟",
        "Kamu adalah bukti bahwa kerja keras membuahkan hasil 💼",
        "Jangan pernah menyerah, karena kesuksesan hanya untuk mereka yang bertahan 🚀",
        "Setiap hari adalah kesempatan untuk menjadi versi terbaik dari dirimu 🌞",
        "Kamu punya potensi untuk mencapai hal-hal luar biasa 🌟",
        "Jangan biarkan rasa takut menghentikanmu, kamu lebih kuat dari itu 💪",
        "Kesuksesan adalah hasil dari keberanian untuk mencoba dan gagal 🌈",
        "Kamu adalah inspirasi bagi orang-orang di sekitarmu ✨",
        "Jangan pernah berhenti bermimpi, karena mimpi adalah bahan bakar hidupmu 🌟",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Kamu punya kekuatan untuk mengubah hidupmu sendiri 🌍",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah pahlawan dalam cerita hidupmu sendiri 🦸‍♂️",
        "Jangan biarkan rasa takut menghentikan langkahmu 🚶‍♂️",
        "Mimpi besar membutuhkan usaha besar, jangan menyerah! 💪",
        "Kamu lebih dekat dengan kesuksesan daripada yang kamu pikirkan 🌈",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Jangan pernah berhenti belajar, karena hidup adalah proses belajar 📚",
        "Kamu adalah arsitek dari masa depanmu sendiri 🏗️",
        "Jangan biarkan kegagalan mendefinisikanmu, bangkitlah! 🔥",
        "Setiap usaha yang kamu lakukan adalah investasi untuk masa depanmu 💰",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah inspirasi bagi orang lain, teruslah bersinar ✨",
        "Setiap hari adalah kesempatan untuk memulai lagi 🌅",
        "Jangan biarkan keraguan menghentikanmu, kamu bisa melakukannya! 💪",
        "Kesuksesan dimulai dari keberanian untuk bermimpi besar 🌟",
        "Kamu lebih kuat dari rintangan yang kamu hadapi 💪",
        "Jangan pernah meremehkan kekuatan dari usaha kecil yang konsisten 🛠️",
        "Kamu adalah penulis dari cerita hidupmu sendiri 📖",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya kekuatan untuk mengubah dunia di sekitarmu 🌍",
        "Jangan takut untuk bermimpi besar, karena mimpi adalah awal dari segalanya 🌟",
        "Kamu adalah bukti bahwa kerja keras membuahkan hasil 💼",
        "Jangan pernah menyerah, karena kesuksesan hanya untuk mereka yang bertahan 🚀",
        "Setiap hari adalah kesempatan untuk menjadi versi terbaik dari dirimu 🌞",
        "Kamu punya potensi untuk mencapai hal-hal luar biasa 🌟",
        "Jangan biarkan rasa takut menghentikanmu, kamu lebih kuat dari itu 💪",
        "Kesuksesan adalah hasil dari keberanian untuk mencoba dan gagal 🌈",
        "Kamu adalah inspirasi bagi orang-orang di sekitarmu ✨",
        "Jangan pernah berhenti bermimpi, karena mimpi adalah bahan bakar hidupmu 🌟",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Kamu punya kekuatan untuk mengubah hidupmu sendiri 🌍",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah pahlawan dalam cerita hidupmu sendiri 🦸‍♂️",
        "Jangan biarkan rasa takut menghentikan langkahmu 🚶‍♂️",
        "Mimpi besar membutuhkan usaha besar, jangan menyerah! 💪",
        "Kamu lebih dekat dengan kesuksesan daripada yang kamu pikirkan 🌈",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Jangan pernah berhenti belajar, karena hidup adalah proses belajar 📚",
        "Kamu adalah arsitek dari masa depanmu sendiri 🏗️",
        "Jangan biarkan kegagalan mendefinisikanmu, bangkitlah! 🔥",
        "Setiap usaha yang kamu lakukan adalah investasi untuk masa depanmu 💰",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah inspirasi bagi orang lain, teruslah bersinar ✨",
        "Setiap hari adalah kesempatan untuk memulai lagi 🌅",
        "Jangan biarkan keraguan menghentikanmu, kamu bisa melakukannya! 💪",
        "Kesuksesan dimulai dari keberanian untuk bermimpi besar 🌟",
        "Kamu lebih kuat dari rintangan yang kamu hadapi 💪",
        "Jangan pernah meremehkan kekuatan dari usaha kecil yang konsisten 🛠️",
        "Kamu adalah penulis dari cerita hidupmu sendiri 📖",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya kekuatan untuk mengubah dunia di sekitarmu 🌍",
        "Jangan takut untuk bermimpi besar, karena mimpi adalah awal dari segalanya 🌟",
        "Kamu adalah bukti bahwa kerja keras membuahkan hasil 💼",
        "Jangan pernah menyerah, karena kesuksesan hanya untuk mereka yang bertahan 🚀",
        "Setiap hari adalah kesempatan untuk menjadi versi terbaik dari dirimu 🌞",
        "Kamu punya potensi untuk mencapai hal-hal luar biasa 🌟",
        "Jangan biarkan rasa takut menghentikanmu, kamu lebih kuat dari itu 💪",
        "Kesuksesan adalah hasil dari keberanian untuk mencoba dan gagal 🌈",
        "Kamu adalah inspirasi bagi orang-orang di sekitarmu ✨",
        "Jangan pernah berhenti bermimpi, karena mimpi adalah bahan bakar hidupmu 🌟",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Kamu punya kekuatan untuk mengubah hidupmu sendiri 🌍",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah pahlawan dalam cerita hidupmu sendiri 🦸‍♂️",
        "Jangan biarkan rasa takut menghentikan langkahmu 🚶‍♂️",
        "Mimpi besar membutuhkan usaha besar, jangan menyerah! 💪",
        "Kamu lebih dekat dengan kesuksesan daripada yang kamu pikirkan 🌈",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Jangan pernah berhenti belajar, karena hidup adalah proses belajar 📚",
        "Kamu adalah arsitek dari masa depanmu sendiri 🏗️",
        "Jangan biarkan kegagalan mendefinisikanmu, bangkitlah! 🔥",
        "Setiap usaha yang kamu lakukan adalah investasi untuk masa depanmu 💰",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah inspirasi bagi orang lain, teruslah bersinar ✨",
        "Setiap hari adalah kesempatan untuk memulai lagi 🌅",
        "Jangan biarkan keraguan menghentikanmu, kamu bisa melakukannya! 💪",
        "Kesuksesan dimulai dari keberanian untuk bermimpi besar 🌟",
        "Kamu lebih kuat dari rintangan yang kamu hadapi 💪",
        "Jangan pernah meremehkan kekuatan dari usaha kecil yang konsisten 🛠️",
        "Kamu adalah penulis dari cerita hidupmu sendiri 📖",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya kekuatan untuk mengubah dunia di sekitarmu 🌍",
        "Jangan takut untuk bermimpi besar, karena mimpi adalah awal dari segalanya 🌟",
        "Kamu adalah bukti bahwa kerja keras membuahkan hasil 💼",
        "Jangan pernah menyerah, karena kesuksesan hanya untuk mereka yang bertahan 🚀",
        "Setiap hari adalah kesempatan untuk menjadi versi terbaik dari dirimu 🌞",
        "Kamu punya potensi untuk mencapai hal-hal luar biasa 🌟",
        "Jangan biarkan rasa takut menghentikanmu, kamu lebih kuat dari itu 💪",
        "Kesuksesan adalah hasil dari keberanian untuk mencoba dan gagal 🌈",
        "Kamu adalah inspirasi bagi orang-orang di sekitarmu ✨",
        "Jangan pernah berhenti bermimpi, karena mimpi adalah bahan bakar hidupmu 🌟",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Kamu punya kekuatan untuk mengubah hidupmu sendiri 🌍",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah pahlawan dalam cerita hidupmu sendiri 🦸‍♂️",
        "Jangan biarkan rasa takut menghentikan langkahmu 🚶‍♂️",
        "Mimpi besar membutuhkan usaha besar, jangan menyerah! 💪",
        "Kamu lebih dekat dengan kesuksesan daripada yang kamu pikirkan 🌈",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Jangan pernah berhenti belajar, karena hidup adalah proses belajar 📚",
        "Kamu adalah arsitek dari masa depanmu sendiri 🏗️",
        "Jangan biarkan kegagalan mendefinisikanmu, bangkitlah! 🔥",
        "Setiap usaha yang kamu lakukan adalah investasi untuk masa depanmu 💰",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah inspirasi bagi orang lain, teruslah bersinar ✨",
        "Setiap hari adalah kesempatan untuk memulai lagi 🌅",
        "Jangan biarkan keraguan menghentikanmu, kamu bisa melakukannya! 💪",
        "Kesuksesan dimulai dari keberanian untuk bermimpi besar 🌟",
        "Kamu lebih kuat dari rintangan yang kamu hadapi 💪",
        "Jangan pernah meremehkan kekuatan dari usaha kecil yang konsisten 🛠️",
        "Kamu adalah penulis dari cerita hidupmu sendiri 📖",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya kekuatan untuk mengubah dunia di sekitarmu 🌍",
        "Jangan takut untuk bermimpi besar, karena mimpi adalah awal dari segalanya 🌟",
        "Kamu adalah bukti bahwa kerja keras membuahkan hasil 💼",
        "Jangan pernah menyerah, karena kesuksesan hanya untuk mereka yang bertahan 🚀",
        "Setiap hari adalah kesempatan untuk menjadi versi terbaik dari dirimu 🌞",
        "Kamu punya potensi untuk mencapai hal-hal luar biasa 🌟",
        "Jangan biarkan rasa takut menghentikanmu, kamu lebih kuat dari itu 💪",
        "Kesuksesan adalah hasil dari keberanian untuk mencoba dan gagal 🌈",
        "Kamu adalah inspirasi bagi orang-orang di sekitarmu ✨",
        "Jangan pernah berhenti bermimpi, karena mimpi adalah bahan bakar hidupmu 🌟",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Kamu punya kekuatan untuk mengubah hidupmu sendiri 🌍",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🚶‍♀️",
        "Setiap tantangan adalah peluang untuk tumbuh dan belajar 🌱",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah pahlawan dalam cerita hidupmu sendiri 🦸‍♂️",
        "Jangan biarkan rasa takut menghentikan langkahmu 🚶‍♂️",
        "Mimpi besar membutuhkan usaha besar, jangan menyerah! 💪",
        "Kamu lebih dekat dengan kesuksesan daripada yang kamu pikirkan 🌈",
        "Setiap langkah kecil membawa kamu lebih dekat ke tujuanmu 🛤️",
        "Jangan pernah berhenti belajar, karena hidup adalah proses belajar 📚",
        "Kamu adalah arsitek dari masa depanmu sendiri 🏗️",
        "Jangan biarkan kegagalan mendefinisikanmu, bangkitlah! 🔥",
        "Setiap usaha yang kamu lakukan adalah investasi untuk masa depanmu 💰",
        "Kamu punya potensi besar, jangan sia-siakan! 🌟",
        "Hidup adalah perjalanan, nikmati setiap momennya 🚀",
        "Jangan takut mencoba hal baru, itu adalah cara untuk tumbuh 🌱",
        "Kamu adalah inspirasi bagi orang lain, teruslah bersinar ✨",
        "Setiap hari adalah kesempatan untuk memulai lagi 🌅",
        "Jangan biarkan keraguan menghentikanmu, kamu bisa melakukannya! 💪",
        "Kesuksesan dimulai dari keberanian untuk bermimpi besar 🌟",
        "Kamu lebih kuat dari rintangan yang kamu hadapi 💪",
        "Jangan pernah meremehkan kekuatan dari usaha kecil yang konsisten 🛠️",
        "Kamu adalah penulis dari cerita hidupmu sendiri 📖",
        "Jangan biarkan kegagalan sementara menghentikan langkahmu 🦵"
    ]

pesan_tebakan = [
            "Kenapa ikan tidak pernah ketabrak kapal? Karena ikan selalu pakai Google Maps 🐟",
            "Apa bedanya kamu sama kalender? Kalender punya tanggal, kamu punya aku ❤️",
            "Kenapa komputer suka ngambek? Karena dia butuh 'refresh' 🔄",
            "Apa yang selalu basah meskipun di bawah terik matahari? Bayanganmu 🌞",
            "Kenapa matematika tidak pernah salah? Karena dia selalu punya solusi 📐",
            "Kenapa burung tidak pernah pergi ke sekolah? Karena dia sudah punya sayap untuk belajar terbang 🐦",
            "Apa yang selalu naik tapi tidak pernah turun? Umurmu 🎂",
            "Kenapa sepatu tidak pernah bertengkar? Karena mereka selalu berjalan beriringan 👟",
            "Apa yang kecil, hitam, dan suka nempel di dinding? Bayanganmu saat lampu mati 🌑",
            "Kenapa kucing suka tidur? Karena dia ingin bermimpi jadi singa 🐱",
            "Apa yang tidak bisa dimakan saat sarapan? Makan siang dan makan malam 🍽️",
            "Kenapa buku selalu diam? Karena dia sudah penuh dengan cerita 📖",
            "Apa yang bisa terbang tanpa sayap? Waktu ⏳",
            "Kenapa komputer tidak pernah lelah? Karena dia punya 'cache' untuk istirahat 💻",
            "Apa yang selalu ada di depanmu tapi tidak bisa kamu lihat? Masa depanmu 🌟"
        ]

pesan_toxic = ["ASU", "KONTOL", "NGENTOT", "BAJINGAN", "FUCK", "NIGGA"]

pesan_salam = [
    "hello", "hai", "halo", "hey", "whatsup", "hei", "hi", "greetings", 
    "selamat pagi", "selamat siang", "selamat sore", "selamat malam", 
    "assalamualaikum", "apa kabar", 
    "hai teman", "halo bro", "halo kawan"
]

pesan_jawaban = [
    "Halo juga! 😊", 
    "Hai, apa kabar? 😄", 
    "Halo! Semoga harimu menyenangkan! 🌟", 
    "Hai, senang bertemu denganmu! 🤗", 
    "Hai teman, apa kabar? 😊", 
    "Halo bro, ada yang bisa dibantu? 💪", 
    "Halo kawan, semoga harimu luar biasa! 🌟", 
    "Hai, semoga kamu selalu sehat dan bahagia! 🌈"
]